import com.mysql.cj.jdbc.ConnectionImpl;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.sql.*;  //fungsi untuk memasukkan komponen sql
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.awt.datatransfer.UnsupportedFlavorException;
//import java.sql.ResultSet;
//import java.sql.Statement;



public class Registrasi extends javax.swing.JFrame {

//   public Statement st;    //fungsi untuk mengaktifkan perintah sql
//   public ResultSet rs;    //fungsi untuk mengeksekusi perintah sql
//   private Connection conn= new koneksi().Connect(); //fungsi untuk melakukan koneksi ke database mysql
    public Registrasi() {
        initComponents();
//    Connection conn = new koneksi().Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtemail = new javax.swing.JTextField();
        btnbatal = new javax.swing.JButton();
        btndaftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Halaman Registrasi");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Email");

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btndaftar.setText("Daftar");
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btndaftar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuser)
                            .addComponent(txtpassword)
                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal)
                    .addComponent(btndaftar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        
            //String url = "insert into tb_user values(?,?,?)";
////            st =conn.createStatement(); 
//            //fungsi cek data tidak boleh kosong
//            if (txtuser.getText().equals("")||
//                    txtemail.getText().equals("")||
//                    txtpassword.getText().equals("")) {
//                JOptionPane.showMessageDialog(null,"Data tidak boleh kosong","Informasi",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//            if (btndaftar.getText()=="Daftar") {
//                String cek ="SELECT * FROM tb_user WHERE username ='" + txtuser.getText() +"'";
//         try {
//            java.sql.Connection conn = (Connection)koneksi.Connect();
//            java.sql.PreparedStatement stat =str (url);
//            stat.setString(1, txtuser.getText());
//            stat.setString(2, txtpassword.getText());
//            stat.setString(3, txtemail.getText());
//                stat.executeUpdate();
//                    JOptionPane.showMessageDialog(null,"Username sudah dipakai...");
////                if (rs.next()) {
//                }catch (SQLException e){
////            }else{
//                //fungsi untuk menyimpan ke table
//             try{
//                 String sql = "INSERT INTO tb_user VALUES (" + txtuser.getText()+
//                        "',"+txtemail.getText()+
//                        "',"+txtpassword.getText()+")";
//                 java.sql.Connection conn = (Connection)koneksi.Connect();
//                 java.sql.PreparedStatement pst=conn.prepareStatement(sql);
//                 pst.execute();
//                 JOptionPane.showConfirmDialog(null, "berhasil daftar");
//                 this.setVisible(false);
//                 new Login().setVisible(true);
////                st.execute(sql);
//        } catch (Exception t) {
//                JOptionPane.showMessageDialog(this,t.getMessage());
//        }
////                JOptionPane.showMessageDialog(null,"Data User berhasil disimpan");
//                }
//       String username = txtuser.getText();
//       String password = txtpassword.getText();
//       String email = txtemail.getText();
//       
//       try {
//        Statement statment = (Statement) koneksi.Connect();
//        statment.executeUpdate("INSERT INTO tb_user ('"+ username +"','"+password+"','"+email+"') VALUES (?, ?, ?);");
//        statment.close ();
//        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
//        new Login().show();
//        this.dispose();
//       }catch (Exception t){
//            JOptionPane.showMessageDialog(null, "data gagal disimpan");
//       }
    String username = txtuser.getText();
    String password = txtpassword.getText();
    String email = txtemail.getText();

    try {
        Connection connection = koneksi.Connect(); // Pastikan koneksi.Connect() mengembalikan objek Connection
        String query = "INSERT INTO tb_user (username, password, email) VALUES (?, ?, ?)";

        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, password);
            preparedStatement.setString(3, email);

            preparedStatement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            new Login().show();
            this.dispose();
        }
    } catch (SQLException t) {
        t.printStackTrace(); // Tampilkan stack trace untuk membantu identifikasi kesalahan
        JOptionPane.showMessageDialog(null, "Data gagal disimpan");
    }
        
    }//GEN-LAST:event_btndaftarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().show();
//         this.hide();
//         Login back = new Login();
//        back.setVisible(true);
    }//GEN-LAST:event_btnbatalActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrasiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrasiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrasiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrasiJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
